type: default-flatpaks
system:
  install:
    - com.bitwarden.desktop
    - org.chromium.Chromium
    - org.kde.kwrite
    - org.mozilla.firefox
    - org.signal.Signal
    - dev.aunetx.deezer
    - com.spotify.Client
    - md.obsidian.Obsidian
    - org.qbittorrent.qBittorrent
    - org.godotengine.Godot
    - org.onlyoffice.desktopeditors
    - com.heroicgameslauncher.hgl
    - com.valvesoftware.Steam
    - org.freedesktop.Platform.VulkanLayer.MangoHud//23.08
    - org.freedesktop.Platform.VulkanLayer.OBSVkCapture//23.08
    - com.obsproject.Studio
    - com.obsproject.Studio.Plugin.OBSVkCapture
    - com.obsproject.Studio.Plugin.Gstreamer

