type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
install:
  # Add your own below:
  - wireguard-tools
  - libatomic # Required for noise-cancelling
  - pavucontrol-qt
  - neovim
  - starship
  - mpv
  - bat
  - wezterm
  - yt-dlp
  - btop
  - papirus-icon-theme
  - timeshift
  - openfortivpn
  - plasma-nm-fortisslvpn
  - NetworkManager-fortisslvpn
# These RPMs will be removed from the system image. This step happens during
# image build, BEFORE installing custom RPMs (from the "rpm.install" category).
remove:
  # Remove the native firefox (from Fedora) in favor of the Flatpak.
  - firefox
  - firefox-langpacks
  - vim-enhanced
  - vim-common
  - vim-minimal
  - google-noto-sans-javanese-fonts
  - google-noto-sans-balinese-fonts
  - google-noto-sans-sundanese-fonts
