name: kukule
description: Fedora tailored to my needs

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
  - from-file: packages.yml
  - from-file: fonts.yml
  - from-file: flatpaks.yml
  - from-file: signing.yml
